"""Abstract base class for all trading strategies."""

from abc import ABC, abstractmethod
from dataclasses import dataclass

import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    symbol: str
    market: str
    action: str  # buy, sell, hold
    strength: float  # 0.0 to 1.0
    stop_loss_cents: int
    price_cents: int
    reason: str
    strategy_name: str
    indicator_data: dict  # raw indicator values for journal


class BaseStrategy(ABC):
    """All strategies inherit from this. Implement generate_signals()."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy identifier."""
        ...

    @abstractmethod
    def generate_signals(self, df: pd.DataFrame, symbol: str, market: str) -> list[Signal]:
        """Analyze price data and return trading signals.

        Args:
            df: OHLCV DataFrame with columns: open, high, low, close, volume.
                All prices in cents. Index is UTC datetime.
            symbol: Instrument symbol (e.g., "AAPL", "BTC/AUD", "BHP.AX")
            market: Market identifier ("us", "crypto", "asx")

        Returns:
            List of Signal objects (may be empty if no action).
        """
        ...
